language: node_js
cache:
  yarn: true
  directories: node_modules
node_js:
- '7'
services:
- docker
env:
  matrix:
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  global:
  - secure: D9P/2tkFg2B1bZKBMQSCHHDvMOXfMfxYIoUyZPomLelnxwBKywuwnqi80XcIW5O8VL4iUyDHjndLYEfnvBz0B6F4aAdhBWvNWxFK/LMzUejuw1rdhU3X5P2cwOiT70cAgCfRiVOPTf1tMcS/QK2+ent70a6IwRzANHYxTqwcIUf2spHkORssk8XL99Mbt+COhzXW+Iekt45UhhdfXT46wuHGvsrG3tvlNSC7OAk1kWRWvzxCxU/7z6kqtjGTiW8cBP+XLA/YEVYKttUHWKcQeJiZBFktMv1JzjrdGpEhJzUyNSKuLx5UrodGUNM8gFPyZOj2DzX68nfWIzEpKTwB7IbVmJF00XeoVAyBUI4nnaiseidBXgkOggBbgRTI4r8JeE6jN5V2DJI6PCK4GxXWoNlZ2Skdqv9Gq6LltXgvR1T+XUg1MI1hlo5FuRwCT54goNFiMWZi58Bd6zXhXF8nAZC4CjENY4iluDSrpkNonY2XVnljl3y8IvfiMGqXAoCrD2gXztHQsjrr7p84aHOycu7zn9WXy8DJcGTVLvidLtT4ve1LUwSaagHma/JiSbiIMcsKMKafNlcHOZuJJIZxulzx1Lut+dyLGvUJM/jnPJoBLvGhxDfsRTpXbdgk7gHEvLsk7jSU8QER8TLQDZ6g0FW2O8XV2YSW4ZpW2DHkqCA=
  - secure: Y05H8fZ7m3kY9k9qCfGH1krAYrvLLE8suIpyaak9QUza4UsHddYqb6LWVeXJloFZrnnRkVrl5BaKqOOXzjcgqXJfXkMGZmM08B3GkbHRG0o8xqy3KGlLBYmFg2nDQpK57DhowtLNWUxnnNqhOdWtQSfTua3CU+OCb+Ucjn4VLj6sW3I2Ul+2s/GcxitmlNx7E+NA4UBYdKwfe1bY54ZwoOHOtCSxUQYltu3Hpc8hEK9WultRxJykYHgxnLJsahjjEr8ZC4EdI7By7UbGJPwfUB9S2/8q9Zm+hpiTA/YFWfHVqkVUYjAOyepmhDqmE0qEZW/FhAzlNyGBAhkQfg2oMrV78NKsMbDDYpfGHrXO2DBLWYfKfaOH450olzpjkkeQbx7SvnNajd99NBkqs7zZczRqXi/TQ4A7R7flclv4sMt+FH1SYERJ9p76J4x4fZho8TjXHABdCudRdBbeWJAqTcFU168RftPUv7kudArEulyMl69CT/r+/HIbJFKOxcNsGo3ot8pilwKrp/8+BrDKJ3lFcyTSKVjn9I8TXFrNI3zM22+Fn+FsGQKoiS9tAzg2sdm4zRyI9lL2JmB8rsM3YBYjeycWuUCJpbX9AgUqPQCO0PLtDT5yNJkpvPc6YkqtwdJCFq1yrJhHeWIvqdKpa5hzC2Sf5UeZ7gMbfFelWNc=
before_install:
- yarn install
script:
- yarn flow
- yarn lint
- openssl aes-256-cbc -K $encrypted_129cbaf6d0a3_key -iv $encrypted_129cbaf6d0a3_iv
  -in deployment/client-secret.json.enc -out client-secret.json -d
- deployment/setup_gcloud
after_success:
- docker build -t floq-timebot .
- docker run -d floq-timebot
- docker ps -a
- deployment/deploy
notifications:
  slack:
    secure: GtuLHv4Mdz6qaRxbtL1ip+XVqamP18Fb7eB/WYJts7KpXpw1rnG34d26FZQGXRUFa2EnUWKCQs42ckFJjInQ5MYRnCWNxhpquEvbfMX6JMt3KJPV2CgRjXKi3nCoENN2bVoywlFbZQuCbuVrStCD/g3eWBI3BPGxFMRGMw+9Fkk+tCZBDueIwopKye5jkb4y57Ga4fnlEuaQmLYnB08emhSq3cJ1xUU2zORiCPiAnr6YqjkdnscpCS78N/MQhiSK7En10JK7vAF3NKqKf4Uxz0nSe3LCDEbmm0+zqgn9H5nB4V3oi8QoqMvoEmn+15Z+2y4gcwG48yJ3YoKSPjqZpH8FFVE2tUEZv6JC2mqjK1EZz4eXz5QvySwiAAo3WzZIVXE2aS0JH0G6ESMLFnKKgk/4+3lEqQN07bppmLb4Jvw200zRq5887kyWODRJG8MsaJ2Q5a+eD93fX1WB6gIR59M/V8kUl32XBcyVnk4vf4G9c5Fr6NrhRSiZrnAwXNpMunPnjEdap4Y3TNxHxkPbrPy1A3LYOoIC8sR2MKg2gVxyb+A5DOMQoWdymx8cqDLioO0DtAZ9jU/7Mr7eUxvbCAnHbbc1ZtNeXLSiGOZ4wJeZsV7+9PMztvW+2Y7H17Z/vosMj9x0Vo/i1AjxP0bbzLzn7pOZmRUKXRxfiVjhYgA=
